WIFI_SSID = 'The Last Lanbender'
WIFI_PASS = 'Hq%)tX3!Kw'
TELEGRAM_BOT_TOKEN = '5371396616:AAELiyD9OkGEOGrxV1JVVvOb2bVDlLmyrNs'
TELEGRAM_CHAT_ID = '1084139144'

UBIDOTS_TOKEN = "BBUS-L4gOxlVC6AgDN6ZjXUqKOFasKqS8Ou"
UBIDOTS_DEVICE_LABEL = "picowhboard"
VIBRATION_SENSOR_VARIABLE = "sensor"
ALARM_VARIABLE = "Alarm"